# Generated by Django 3.2.3 on 2021-05-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_joinig',
            field=models.CharField(max_length=30),
        ),
    ]
