# Generated by Django 3.2.3 on 2021-05-31 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0002_alter_employee_date_of_joinig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employe_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_joinig',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='desgination',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
